package keymanager

import (
	"sync"

	"github.com/prometheus/client_golang/prometheus"
)

const (
	// labelRuntime is the label for the runtime identifier.
	labelRuntime = "runtime"
	// labelChurp is the label for the CHURP identifier.
	labelChurp = "churp"
	// labelMethod is the label for the CHURP's method name.
	labelMethod = "method"
)

var (
	computeRuntimeCount = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_compute_runtime_count",
			Help: "Number of compute runtimes using the key manager.",
		},
		[]string{labelRuntime},
	)

	policyUpdateCount = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_policy_update_count",
			Help: "Number of key manager policy updates.",
		},
		[]string{labelRuntime},
	)

	consensusEphemeralSecretEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_consensus_ephemeral_secret_epoch_number",
			Help: "Epoch number of the latest ephemeral secret.",
		},
		[]string{labelRuntime},
	)

	consensusMasterSecretGenerationNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_consensus_master_secret_generation_number",
			Help: "Generation number of the latest master secret.",
		},
		[]string{labelRuntime},
	)

	consensusMasterSecretRotationEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_consensus_master_secret_rotation_epoch_number",
			Help: "Epoch number of the latest master secret rotation.",
		},
		[]string{labelRuntime},
	)

	consensusMasterSecretProposalEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_consensus_master_secret_proposal_epoch_number",
			Help: "Epoch number of the latest master secret proposal.",
		},
		[]string{labelRuntime},
	)

	consensusMasterSecretProposalGenerationNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_consensus_master_secret_proposal_generation_number",
			Help: "Generation number of the latest master secret proposal.",
		},
		[]string{labelRuntime},
	)

	enclaveEphemeralSecretEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_ephemeral_secret_epoch_number",
			Help: "Epoch number of the latest ephemeral secret loaded into the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveMasterSecretGenerationNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_master_secret_generation_number",
			Help: "Generation number of the latest master secret as seen by the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveMasterSecretProposalEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_master_secret_proposal_epoch_number",
			Help: "Epoch number of the latest master secret proposal loaded into the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveMasterSecretProposalGenerationNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_master_secret_proposal_generation_number",
			Help: "Generation number of the latest master secret proposal loaded into the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveGeneratedMasterSecretEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_generated_master_secret_epoch_number",
			Help: "Epoch number of the latest master secret generated by the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveGeneratedMasterSecretGenerationNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_generated_master_secret_generation_number",
			Help: "Generation number of the latest master secret generated by the enclave.",
		},
		[]string{labelRuntime},
	)

	enclaveGeneratedEphemeralSecretEpochNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_enclave_generated_ephemeral_secret_epoch_number",
			Help: "Epoch number of the latest ephemeral secret generated by the enclave.",
		},
		[]string{labelRuntime},
	)
	churpThresholdNumber = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_churp_threshold_number",
			Help: "Degree of the secret-sharing polynomial",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpExtraSharesNumber = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_churp_extra_shares_number",
			Help: "Minimum number of extra shares.",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpHandoffNumber = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_churp_handoff_number",
			Help: "Epoch number of the last handoff",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpNextHandoffNumber = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_churp_next_handoff_number",
			Help: "Epoch number of the next handoff",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpHandoffInterval = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_churp_handoff_interval",
			Help: "Handoff interval in epochs",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpCommitteeSize = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_churp_committee_size",
			Help: "Number of nodes in the committee",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpSubmittedApplicationsTotal = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_churp_submitted_applications_total",
			Help: "Number of submitted applications",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpConfirmedApplicationsTotal = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "oasis_worker_keymanager_churp_confirmed_applications_total",
			Help: "Number of confirmed applications",
		},
		[]string{labelRuntime, labelChurp},
	)
	churpEnclaveRPCLatency = prometheus.NewSummaryVec(
		prometheus.SummaryOpts{
			Name: "oasis_worker_keymanager_churp_enclave_rpc_latency_seconds",
			Help: "Latency of enclave rpc calls in seconds.",
		},
		[]string{labelRuntime, labelChurp, labelMethod},
	)
	churpEnclaveRPCFailures = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "oasis_worker_keymanager_churp_enclave_rpc_failures_total",
			Help: "Number of failed enclave rpc calls.",
		},
		[]string{labelRuntime, labelChurp, labelMethod},
	)

	keymanagerWorkerCollectors = []prometheus.Collector{
		computeRuntimeCount,
		policyUpdateCount,
		consensusEphemeralSecretEpochNumber,
		consensusMasterSecretGenerationNumber,
		consensusMasterSecretRotationEpochNumber,
		consensusMasterSecretProposalEpochNumber,
		consensusMasterSecretProposalGenerationNumber,
		enclaveEphemeralSecretEpochNumber,
		enclaveMasterSecretGenerationNumber,
		enclaveMasterSecretProposalEpochNumber,
		enclaveMasterSecretProposalGenerationNumber,
		enclaveGeneratedMasterSecretEpochNumber,
		enclaveGeneratedMasterSecretGenerationNumber,
		enclaveGeneratedEphemeralSecretEpochNumber,
		churpThresholdNumber,
		churpExtraSharesNumber,
		churpHandoffNumber,
		churpNextHandoffNumber,
		churpHandoffInterval,
		churpCommitteeSize,
		churpSubmittedApplicationsTotal,
		churpConfirmedApplicationsTotal,
		churpEnclaveRPCLatency,
		churpEnclaveRPCFailures,
	}

	metricsOnce sync.Once
)

func initMetrics() {
	metricsOnce.Do(func() {
		prometheus.MustRegister(keymanagerWorkerCollectors...)
	})
}
